import Head from "next/head";
import { GetStaticProps } from "next";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import PostList from "../components/PostList";
import { fetchPosts } from "../utils/api";
import { Post } from "../types";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

interface HomePageProps {
  posts: Post[];
}

const HomePage: React.FC<HomePageProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Blog viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <PostList posts={posts} />
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const posts = await fetchPosts();
  return { props: { posts } };
};

export default HomePage;
